[theme]
primaryColor="#0066cc"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
enableCORS = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[deprecation]
showPyplotGlobalUse = false

[theme]
base = "light"

[runner]
fastReruns = true 